spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-name: ${CLIENT_NAME}
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Taskflow
server:
  port: 9090
